//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VutaCheck01.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FluidIntakeDetail
    {
        public int FluidIntakeId { get; set; }
        public int VitaminFluidId { get; set; }
        public System.DateTime FluidIntakeDate { get; set; }
        public string FluidIntakeTime { get; set; }
        public string AdditionalInfo { get; set; }
        public int UserId { get; set; }
    
        public virtual FluidVitaminDetail FluidVitaminDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
