//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VutaCheck01.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FluidVitaminDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FluidVitaminDetail()
        {
            this.FluidIntakeDetails = new HashSet<FluidIntakeDetail>();
        }
    
        public int VitaminFluidId { get; set; }
        public int VitaminId { get; set; }
        public string FluidSource { get; set; }
        public Nullable<bool> IsFluidSourceDelete { get; set; }
    
        public virtual VitaminDetail VitaminDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FluidIntakeDetail> FluidIntakeDetails { get; set; }
    }
}
