//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VutaCheck01.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodIntakeDetail
    {
        public int FoodIntakeId { get; set; }
        public int FoodId { get; set; }
        public System.DateTime FoodIntakeDate { get; set; }
        public string FoodIntakeTime { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual FoodDetail FoodDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
