//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VutaCheck01.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptom
    {
        public int SymptomId { get; set; }
        public string SymptomDescription { get; set; }
        public Nullable<bool> IsSymptomDelete { get; set; }
    }
}
