//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VutaCheck01.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitaminSymptomRelation
    {
        public int RelationId { get; set; }
        public Nullable<int> SymptomId { get; set; }
        public Nullable<int> VitaminId { get; set; }
        public bool IsRelationDelete { get; set; }
    }
}
